modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/AE2-Insert-Export-Card/issues/new/choose"
[[mods]]
modId="ae2insertexportcard"
version="${file.jarVersion}"
displayName="AE2 Insert Export Card"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ae2-insert-export-card"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds a Insert and Export Card."

[[dependencies.ae2insertexportcard]]
    modId="ae2"
    mandatory=true
    versionRange="[12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2insertexportcard]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2insertexportcard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
